### ISSUE TITLE
When you have lots of exit nodes (i.e. Mullvad) - UI breaks

### ISSUE THREAD

**Issue by Valien** [neuralinkcorp/tsui#14]
Love the product. Very very cool CLI UI.

If you run `tsui` and hit the down arrow for the `exit nodes` and if you a lot of exit nodes the screen layout/formatting breaks a little bit and you have to hit the up arrow to get back to the previous menu.

More of a paging/rendering issue with the long list of exit nodes.

**Comment by kognise** [comment]
Fixed in d1fd44cce733a65eca4df4e92ca5f8c2f029e7ce and will be released in the next 30 minutes as v0.1.0. Your client should auto-update. Thanks for the report!
